# Generated by Django 5.1.2 on 2024-11-04 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id_checkin', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_horario_checkin', models.DateTimeField(auto_now_add=True)),
                ('data_horario_checkout', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], default='checkin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id_responsavel', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('relacionamento_crianca', models.CharField(max_length=255)),
                ('telefone_responsavel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username_usuario', models.CharField(max_length=255)),
                ('senha_usuario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id_crianca', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome_crianca', models.CharField(max_length=255)),
                ('classificacao', models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante'), ('congregado', 'Congregado')], max_length=10)),
                ('sala', models.CharField(choices=[('kids 1', 'Kids 1'), ('kids 2', 'Kids 2'), ('kids 3', 'Kids 3'), ('teens', 'Teens'), ('adolescentes', 'Adolescentes')], max_length=12)),
                ('id_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controle')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crianca')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='ControleResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.controle')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.responsavel')),
            ],
        ),
        migrations.AddField(
            model_name='controle',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
    ]
