# Generated by Django 5.1.2 on 2024-11-04 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='nome_crianca',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='nome_responsavel',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='crianca',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
