# Generated by Django 5.1.2 on 2024-11-13 23:52

import datetime
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nome_crianca_crianca_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha_usuario',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='controle',
            name='status',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], default='checkin', max_length=10, validators=[main.validators.StatusValidator]),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='classificacao',
            field=models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante'), ('congregado', 'Congregado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[main.validators.DataNascimentoValidator]),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='nome',
            field=models.CharField(max_length=255, validators=[main.validators.NomeValidator]),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='sala',
            field=models.CharField(choices=[('kids 1', 'Kids 1'), ('kids 2', 'Kids 2'), ('kids 3', 'Kids 3'), ('teens', 'Teens'), ('adolescentes', 'Adolescentes')], max_length=12),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(max_length=255, validators=[main.validators.NomeValidator]),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone_responsavel',
            field=models.CharField(max_length=11, validators=[main.validators.TelefoneValidator]),
        ),
    ]
