# Generated by Django 5.1.2 on 2024-11-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_senha_usuario_usuario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
