# Generated by Django 5.1.2 on 2024-11-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_usuario_user_rename_id_usuario_user_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='observacao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
