# Generated by Django 5.1.2 on 2024-11-14 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_crianca_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='responsaveis',
            field=models.ManyToManyField(related_name='criancas', to='main.responsavel'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
