# Generated by Django 5.1.2 on 2024-11-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_crianca_responsaveis_alter_crianca_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_criancas'),
        ),
    ]
