# Generated by Django 5.1.2 on 2024-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_crianca_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
