# Generated by Django 5.1.2 on 2024-11-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_controle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='id_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.controle'),
        ),
    ]
