# Generated by Django 5.1.2 on 2024-11-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_crianca_id_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crianca'),
        ),
    ]
